language: java
sudo: false
jdk:
  - openjdk8
script:
# To get rid of  the "Downloading/Downloaded" lines we use: 
# --batch-mode  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  travis_wait 15 mvn mvn clean install --batch-mode  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
